# -*- coding: utf-8 -*-
"""DataPrep.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-p2d9aNWZR7ha0QwvyiClQWKIHl2-dz
"""

import yfinance as yf

tickers = ["AAPL","MSFT","GOOG","SPY"]
df = yf.download(tickers, start="2024-01-01", end="2025-05-17")["Adj Close"]
df.to_csv("prices.csv")
print("Saved prices.csv")